[[redirects]]
  from = "https://media.jps.fyi"
  to = "/wall"
  status = 200

[[redirects]]
  from = "https://api.jps.fyi"
  to = "/wall"
  status = 200

[[redirects]]
  from = "https://media.jps.fyi/*"
  to = "https://res.cloudinary.com/jaysella/:splat"
  status = 200

[[redirects]]
  from = "https://api.jps.fyi/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/m/*"
  to = "https://res.cloudinary.com/jaysella/:splat"
  status = 200
